<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.0.0</Version>
    <Authors>xHotspot Contributors</Authors>
    <Company>xHotspot</Company>
    <Product>xHotspot Automatic Mobile Hotspot Manager</Product>
  </PropertyGroup>
</Project>
