<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWpf>true</UseWpf>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>..\..\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\icon.ico" Link="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\xHotspot.Core\xHotspot.Core.csproj" />
  </ItemGroup>
</Project>
